import React from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

export async function getStaticProps() {
  const promises = [];
  const data = await fetch(`${process.env.API}/slp/history`, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  }).then((res) => res.json());

  data.forEach((datum) => {
    promises.push(fetch(`${process.env.API}/slp/today?eth=${datum.eth}`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
    }).then((res) => res.json()).then((json) => ({
      eth: datum.eth,
      name: datum.name,
      today: json.today,
      snapshots: datum.snapshots,
    })));
  });

  const accounts = await Promise.all(promises).then((result) => result);
  return {
    revalidate: 1,
    props: { accounts },
  };
}

function DisplayAccounts(props) {
  const { accounts } = props;
  const currentDate = new Date();
  if (accounts) {
    const listItems = accounts.map((account) => {
      const snapshots = account.snapshots.map((snapshot) => {
        const date = new Date(snapshot.date);
        return (
          <li>
            <ul>
              <li>
                { `${date.toLocaleDateString()} PST = ${snapshot.dayTotal}` }
              </li>
              <li>
                { `Total: ${snapshot.currentTotal}` }
              </li>
            </ul>
          </li>
        );
      });
      return (
        <ul>
          <li>{ account.eth }</li>
          <li>{ account.name }</li>
          <li>{ `Today at ${currentDate.toLocaleDateString()} PST = ${account.today}` }</li>
          { snapshots }
        </ul>
      );
    });
    return (
      <div>{listItems}</div>
    );
  }
}

export default function Home({ accounts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nasacademy Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DisplayAccounts accounts={accounts} />
      </main>

      <footer className={styles.footer} />
    </div>
  );
}
