import React from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

export async function getStaticProps() {
  const data = await fetch(`${process.env.API}/slp/history`, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  }).then((res) => res.json());
  return {
    revalidate: 1,
    props: { accounts: data },
  };
}

function DisplayAccounts(props) {
  const { accounts } = props;
  if (accounts) {
    const listItems = accounts.map((account) => {
      const snapshots = account.snapshots.map((snapshot) => {
        const date = new Date(snapshot.date);
        return (
          <li>
            <ul>
              <li>
                Total:
                {' '}
                { snapshot.currentTotal }
              </li>
              <li>
                Date:
                {' '}
                { date.toLocaleDateString() }
              </li>
            </ul>
          </li>
        );
      });
      return (
        <ul>
          <li>{ account.name }</li>
          <li>{ account.eth }</li>
          { snapshots }
        </ul>
      );
    });
    return (
      <div>{listItems}</div>
    );
  }
}

export default function Home({ accounts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nasacademy Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DisplayAccounts accounts={accounts} />
      </main>

      <footer className={styles.footer} />
    </div>
  );
}
